image: docker:latest

services:
  - docker:dind

variables:
  CI_REGISTRY_IMAGE: registry.gitlab.com/rameduard/remesas-server-api

before_script:
  - docker login -u gitlab-ci -p "ewFmJzsCmhU5XroNxw25" $CI_REGISTRY_IMAGE

build_image:
  script:
    - echo "Build docker image $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master
