image: docker:latest

before_script:
    - docker info

variables:
  CI_REGISTRY_IMAGE: registry.gitlab.com/rameduard/remesas-server-api

build_image:
  script:
    - echo "Build docker image $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master
